### ISSUE TITLE
Emmake fails for H5make_libsettings: Permission denied

### ISSUE THREAD

**Issue by dhirajnitk** [aertslab/webhdf5#1]
@MaybeJustJames  @aertslab

Tried to run your code on ubuntu 20.04 with hdf 1.13 . H5make_libsettings executable creates H5lib_settings.c whose compilation fails(it seems)

/bin/bash: line 1: ./H5make_libsettings: Permission denied

```
1 warning generated.
/bin/bash: line 1: ./H5make_libsettings: Permission denied
make[2]: *** [Makefile:2772: H5lib_settings.c] Error 1
make[2]: *** Waiting for unfinished jobs....
make[1]: *** [Makefile:1205: all] Error 2
make: *** [Makefile:663: all-recursive] Error 1
```

**Comment by MaybeJustJames** [comment]
Hi @dhirajnitk ,
as you noticed this project has been neglected but I would like to keep the bug open because it is valid
